### ISSUE TITLE
你好，关于dynamic_proxy_pass_module模块的实现和使用能够详细说明一下么？

### ISSUE THREAD

**Issue by fankeke** [wenchaomeng/dengine#1]
这个模块的具体功能和实现方式能说明下么？或者有没有相关资料可以查阅，谢谢。
比如 upstream_degrade_rate /upstream_degrade_force_state 这两个指令具体代表的含义是啥？

**Comment by wenchaomeng** [comment]
模块下面有说明文档，请参考：
https://github.com/wenchaomeng/dengine/tree/master/ngx_dynamic_proxy_pass_module

**Comment by fankeke** [comment]
额。。看了里面的readme文档，不过还是不是很清楚，我猜测一下：
关于degrade_rate，当某个upstream中的server个数不可用的百分比超过这个rate后，整个upstream都将不可用？
然后force_state这个参数就不太清楚了

不过这应该是degrade部分的，这个模块的核心功能从名字上来看是动态路由，但不知道是如何个路由法呢？

还望兄台指明下：）

**Comment by wenchaomeng** [comment]
1、整个模块是做降级用的，即upstream不可用的时候，将请求转移到另外一个upstream
具体到这里的实现，配置了两个upstream，比如：
pool1
pool1#BACKUP
在pool1不可用的时候，将请求转移到pool1#BACKUP
2、force_state用来控制降级的策略
1强制升级，即必须使用pool1
0自动          即在pool1不可用，则降级到pool1#BACKUP，可用则恢复到pool1
-1强制降级，即必须使用pool1#BACKUP
