### ISSUE TITLE
hi，想把dypp模块移到tengine-2.1.2中

### ISSUE THREAD

**Issue by fankeke** [wenchaomeng/dengine#2]
在tengine-2.0.3版本中，dyups模块没有内置，到2.1.2中内置了。所以我改了两个地方
1 config文件中去掉了dyups的include操作
2 在check_upstream_module中把 static ngx_http_upstream_check_peers_t *check_peers_ctx = NULL; 中的static去掉了。（在dypp中引用到了这个结构）

现在可编译链接正常，但是check_upstream_module好像没法工作，具体 表现：
1 后端server检查机制貌似停止了，
2 dypp模块的降级功能应该是依赖在check_upstream模块的检查机制的吧

请问对移植有何建议没？：）

**Comment by wenchaomeng** [comment]
建议先读懂代码的整个调用逻辑，再去移植
看看这本书《深入理解Nginx：模块开发与架构解析》
