### ISSUE TITLE
请问，为啥要重复定义这些结构体呢？比如struct ngx_http_upstream_check_peer_s

### ISSUE THREAD

**Issue by fankeke** [wenchaomeng/dengine#3]
明白了。
1，因为需要引用check模块中的这些结构体来进行成员指定，但是check模块没有公开这些结构体，所以只好自己写出一份来（必须保持和check模块中的成员顺序一致）

2，另外peer[i]中添加了uscf成员，是为了找到peer[i]对应的dypp模块中的dyscf结构体。

－－－－－－－－－－－－－
在dypp模块中，定义了很多和check_upstream模块里面同样名字的模块，请问这是为什么呢？
1 ，比如 ngx_http_upstream_check_peer_shm_t， 还有struct ngx_http_upstream_check_peer_s，

2 ，在使用时候，不会导致冲突么？我看到重新定义的结构体和check模块结构体的成员有不一致的地方？

**Comment by wenchaomeng** [comment]
赞！
